Repository alvesmog/sprintCodeEcommerce, pull requests merged in 2020-04, with the labels that each got.

#14 add pacotes vendas, anuncio, financeiro
  src/main/java/br/com/spring/code/ecommerce/anuncio/Anuncio.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/ListaRepositorioAnuncio.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/RepositorioAnuncio.java
  src/main/java/br/com/spring/code/ecommerce/financeiro/Financeiro.java
  src/main/java/br/com/spring/code/ecommerce/financeiro/Pagamento.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/TipoPessoa.java
  src/main/java/br/com/spring/code/ecommerce/vendas/ListaRepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/vendas/RepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/vendas/Vendas.java
  src/test/java/br/com/spring/code/ecommerce/AppTest.java
Labels: documentation, enhancement

#15 Lógica "Pagamento" e "Venda"
  .gitignore
  README.md
  src/main/java/br/com/spring/code/ecommerce/financeiro/Financeiro.java
  src/main/java/br/com/spring/code/ecommerce/financeiro/ListaRepositorioFinanceiro.java
  src/main/java/br/com/spring/code/ecommerce/financeiro/Pagamento.java
  src/main/java/br/com/spring/code/ecommerce/financeiro/RepositorioFinanceiro.java
  src/main/java/br/com/spring/code/ecommerce/venda/E-commerce - venda e pagto.png
  src/main/java/br/com/spring/code/ecommerce/venda/ListaRepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/venda/RepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/venda/TipoDeEnvio.java
  src/main/java/br/com/spring/code/ecommerce/venda/Venda.java
  src/main/java/br/com/spring/code/ecommerce/vendas/ListaRepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/vendas/RepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/vendas/Vendas.java
Labels: new development

#16 Correções das classes dúvidas e atendimento, criação de um repositóri…
  src/main/java/br/com/spring/code/ecommerce/atendimento/Atendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/RepositorioAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Duvidas.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Interacoes.java
Labels: enhancement, new development

#17 Atualização: Gestão de Pessoas
  src/main/java/br/com/spring/code/ecommerce/App.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/Atendimento.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/Endereco.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/Pessoa.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/PessoaFisica.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/PessoaJuridica.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/RepositorioPessoas.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/TipoPessoa.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/Usuario.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/WebServiceCep.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/dom4j-1.6.1.jar
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceDoApp.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuPessoas.java
Labels: enhancement, new development

#18 [fix] dependencia para o webServiceCep utilizado em `gestaoPessoas`
  pom.xml
Labels: bug

#19 [fix] dependencia para o webServiceCep utilizado em `gestaoPessoas`
  pom.xml
Labels: bug
