Repository alvesmog/sprintCodeEcommerce, pull requests merged in 2020-05, with the labels that each got.

#20 Inclusão de alguns métodos necessários às interfaces que serão criadas
  src/main/java/br/com/spring/code/ecommerce/atendimento/Atendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/EmissorMensagem.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/MensagensAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/RepositorioAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Duvidas.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Interacoes.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/RepositorioDuvidas.java
  src/main/java/br/com/spring/code/ecommerce/venda/ListaRepositorioVendas.java
Labels: new development

#24 Interface produto
  src/main/java/br/com/spring/code/ecommerce/App.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Categoria.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Estado.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/FaixaEtaria.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Produto.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/RepositorioCategorias.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/RepositorioProdutos.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuProdutos.java
Labels: new development

#27 Implementar reorganização proposta + g. pessoas + g. produtos
  .gitignore
  README.md
  pom.xml
  src/main/java/br/com/spring/code/ecommerce/App.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/Atendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/EmissorMensagem.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/MensagensAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/RepositorioAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Duvidas.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Interacoes.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/RepositorioDuvidas.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/CepException.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/CpfCnpjException.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/Endereco.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/Pessoa.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/PessoaFisica.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/PessoaJuridica.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/RepositorioPessoas.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/Usuario.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/ValidadorCpfCnpj.java
  src/main/java/br/com/spring/code/ecommerce/gestaopessoas/WebServiceCep.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Categoria.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Estado.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/FaixaEtaria.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Produto.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/RepositorioCategorias.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/RepositorioProdutos.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceDoApp.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuPessoas.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuProdutos.java
  src/main/java/br/com/spring/code/ecommerce/venda/ListaRepositorioVendas.java
Labels: enhancement

#25 Interface: Venda e Financeiro
  src/main/java/br/com/spring/code/ecommerce/App.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/Anuncio.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/ListaRepositorioAnuncio.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/RepositorioAnuncio.java
  src/main/java/br/com/spring/code/ecommerce/financeiro/Financeiro.java
  src/main/java/br/com/spring/code/ecommerce/gestaoprodutos/Produto.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuVenda.java
  src/main/java/br/com/spring/code/ecommerce/sessao/ControladorSessao.java
  src/main/java/br/com/spring/code/ecommerce/sessao/Sessao.java
  src/main/java/br/com/spring/code/ecommerce/venda/BarraDeProgresso.java
  src/main/java/br/com/spring/code/ecommerce/venda/ListaRepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/venda/RepositorioVendas.java
  src/main/java/br/com/spring/code/ecommerce/venda/Venda.java
Labels: new development

#33 New sub menus
  src/main/java/br/com/spring/code/ecommerce/App.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/Anuncio.java
  src/main/java/br/com/spring/code/ecommerce/anuncio/ListaRepositorioAnuncio.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/Atendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/MensagensAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/atendimento/RepositorioAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Duvidas.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/Interacoes.java
  src/main/java/br/com/spring/code/ecommerce/duvidas/RepositorioDuvidas.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceDoApp.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuAnuncios.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuAtendimento.java
  src/main/java/br/com/spring/code/ecommerce/menuInterface/InterfaceSubMenuDuvidas.java
Labels: enhancement, new development
